name: Update YC Data Cache
on:
  schedule:
    - cron: "0 */6 * * *" # Every 6 hours
  workflow_dispatch: # Manual trigger option

jobs:
  update-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -e .

      - name: Update cache
        run: python scripts/update_cache.py

      - name: Update README timestamp
        run: python scripts/update_readme_timestamp.py

      - name: Commit changes
        run: |
          git config --local user.email "soy@aitor.me"
          git config --local user.name "rodriguezaitor"
          git add data/ README.md
          TIMESTAMP=$(cat data/last_update.txt)
          git diff --quiet && git diff --staged --quiet || git commit -m "Data Update - $TIMESTAMP [skip ci]"
          git push
